### ISSUE TITLE
lesson_2/exercise_6 [wandb] artifact.file() raising an IndexError

### ISSUE THREAD

**Issue by stoufa** [udacity/cd0581-building-a-reproducible-model-workflow-exercises#16]
even when running the solution, I get the following traceback:

```
Traceback (most recent call last):
  File "/path/to/cd0581-building-a-reproducible-model-workflow-exercises/lesson-2-data-exploration-and-preparation/exercises/exercise_6/starter/run.py", line 135, in <module>
    go(args)
  File "/path/to/cd0581-building-a-reproducible-model-workflow-exercises/lesson-2-data-exploration-and-preparation/exercises/exercise_6/starter/run.py", line 23, in go
    artifact_path = artifact.file()
  File "/path/to/anaconda3/envs/mlflow-9bfe8e3af68696f10e0ad9a623577b2921db6aba/lib/python3.9/site-packages/wandb/apis/public.py", line 3946, in file
    return self._download_file(list(manifest.entries)[0], root=root)
IndexError: list index out of range
```

**Comment by stoufa** [comment]
My bad! I forgot to run `artifact.add_file("my_artifact.ext")` before `run.log_artifact(artifact)` in the previous exercise, this is why I'm getting this error! Though, I hope `wandb` replaces this error with a better one, something like:
```
WandbError: Artifact not found.
Make sure to run `artifact.add_file("/path/to/my_artifact.ext")` before `run.log_artifact(artifact)`
```
